### ISSUE TITLE
Jak zrobic

### ISSUE THREAD

**Issue by yamiM0NSTER** [pgorecki/aisd#1]
Jak zrobic to zadanie ja nie wiem co tutaj sie dzieje normalnie poprostu rozwiazania potzreba tutaj tak dla mnie sie wydaje
pozdrawiam serdeznie

**Comment by pgorecki** [comment]
O które zadanie chodzi?

**Comment by yamiM0NSTER** [comment]
Nieważne, nie wylogowałem się z githuba i ktoś trolla zrobił... Przepraszam za kłopot. Chyba, że ktoś serio miał problem i nie pomyślał.
